### ISSUE TITLE
validExpiresOpts issue

### ISSUE THREAD

**Issue by divinity76** [sanjayankur31/fpaste#1]
looking at the source code of fpaste, i find
```py
    validExpiresOpts = ['1800', '21600', '86400', '604800', '2592000']
```
if those are indeed the only valid options, there is 2 issues: 
1: it is not documented in the api docs - http://paste.fedoraproject.org/doc/api/
2: the api does not complain when used with another value, implying the expire date will be honored. (tested 31536000 , aka 1 * 60 * 60 * 24 * 365 , aka 1 year)

if they're not the only valid options, the issue is that fpaste only allow those options :p

**Comment by sanjayankur31** [comment]
So, I haven't actually looked at the sticky notes API recently - (the sticky notes server is a different program maintained by a different person. fpaste is just a client that interacts with the sticky notes server - it does not define the API or anything). I see that these options are defined here, though:

https://github.com/sayakb/sticky-notes/blob/master/app/config/expire.php

The expiry options here in the client are to keep the command line client in line with the options that the web application (http://paste.fedoraproject.org) exposes.
